version: "3"
services:
  app:
    image: node:20.18.0-slim
    container_name: Discord_Bot_dev
    working_dir: /usr/src/app
    
    volumes:
    # node_modules意外のファイルをマウントする
      - type: bind
        source: ./
        target: /usr/src/app
      
    environment:
      - NODE_ENV=production

    command: npm run start

    tty: true