# ベースイメージとして node:20.18.0-slim を使用
FROM node:20.18.0-slim

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# パッケージマネージャーのキャッシュを考慮して依存関係をコピー
COPY package*.json ./

# 依存関係のインストール
RUN npm install

# アプリケーションのソースコードをコンテナにコピー
COPY . .

# 環境変数を設定
ENV NODE_ENV=development

# アプリケーションの起動コマンドを指定
CMD ["npm", "run", "start"]
